# Copyright (c) 2026 The ZMK Contributors
# SPDX-License-Identifier: MIT

# Uncomment to save power by sleeping when idle
# CONFIG_ZMK_SLEEP=y

# Uncomment to enable deep sleep on battery
# CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000
